spring:
  datasource:
    username: sa
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  config:
    import: optional:secrets_prod.yaml
    activate:
      on-profile: test

  application:
    name: DCK
app:
  jwtSecret: 6B58703273357638792F423F4428472B4B6250655368566D597133743677397A244326462948404D635166546A576E5A7234753778214125442A472D4B614E64
  jwtExpirationInMs: 604800000
  cors:
    allowedOrigins: "*"
  max-cell-size: 30

logging:
  level:
    org.hibernate.SQL: DEBUG

info:
  app:
    description: This is a church web application (Dominion city kubwa)
    version: 1.0.0

---

spring:
  config:
    import: optional:secrets_prod.yaml
    activate:
      on-profile: prod
  application:
    name: dck

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
info:
  app:
    description: This is a church web application (Dominion City Kubwa)
    version: 1.0.0

---
server:
  port: 8080
spring:
  config:
    import: optional:secrets_dev.yaml
    activate:
      on-profile: dev
  application:
    name: DCK

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dck
    username: root
    password: 10850106Row
    initialization-mode: always

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
info:
  app:
    description: This is a church web application (Dominion City Kubwa)
    version: 1.0.0
